export const homeObjOne = {
    id: 'about', 
    lightBg: false,
    lightText:true,
    lightTextDesc: true,
    topLine: 'Lorem ipsum',
    headLine: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    descriptionInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../images/4.svg').default,
    alt: 'car',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover', 
    lightBg: true,
    lightText:false,
    lightTextDesc: false,
    topLine: 'Lorem ipsum',
    headLine: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    descriptionInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    buttonLabel: 'Learn More',
    imgStart: false,
    img: require('../../images/1.svg').default,
    alt: 'car',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'signup', 
    lightBg: true,
    lightText:false,
    lightTextDesc: false,
    topLine: 'Lorem ipsum',
    headLine: 'Lorem ipsum dolor sit amet',
    descriptionInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    buttonLabel: 'START NOW',
    imgStart: true,
    img: require('../../images/3.svg').default,
    alt: 'car',
    dark: false,
    primary: false,
    darkText: true,
};